### ISSUE TITLE
Which fork should I use?

### ISSUE THREAD

**Issue by dbolser** [Simplexum/python-bitcointx#17]
I see that this is based on:
- https://github.com/petertodd/python-bitcoinlib or
- https://github.com/dgpv/python-bitcoinlib

So which one should I use?

kthxbi

**Comment by dgpv** [comment]
This is based on https://github.com/petertodd/python-bitcoinlib

https://github.com/dgpv/python-bitcoinlib is just temporary clone of petertodd's repo, that was used before python-bitcointx was created.  https://github.com/dgpv/python-bitcoinlib will not be maintained.

I cannot advise you on what you should use. It is up to you. You may create your own fork and maintain it, if you wish.

**Comment by dbolser** [comment]
Right, I understand. Thanks for carrying this forward. I think the ideal situation would be for you to get co-maintainer status on the 'central' repo, or for the central repo to point (with a caveat) to your fork.

Thanks again,
Dan.

**Comment by dgpv** [comment]
The thing here is that this is not a fork. This is derivative library.

It is not directly compatible - I deliberately changed the module name to 'bitcointx'.

I removed all the network-related code, because:
 - It is not relevant for our product (simplexum.com)
 - We are not ready to expend resources to maintain the code that we do not use

If someone wants the original library with the new functionality that is added to python-bitcointx, they are free to take the code and apply to their python-bitcoinlib fork.

**Comment by dbolser** [comment]
OIC, interesting.
