### ISSUE TITLE
PSBT_Input does not allow full transaction in utxo field for witness inputs

### ISSUE THREAD

**Issue by dgpv** [Simplexum/python-bitcointx#33]
In light of potential large-fee-ransom attacks against autonomous singners of segwit transactions (details: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-August/014843.html https://twitter.com/FreedomIsntSafe/status/1268572922911887360), it is not wise to disallow full-`CTransaction` utxo fields in `PSBT_Input` for segwit inputs, because one of the workarounds for the attacks is supplying full previous transactions for segwit inputs in the same way as done for non-segwit inputs.

I am currently working on a change that would allow to leave `CTransaction` in `utxo` field of `PSBT_Input`, even if the input is segwit, and put `CTxOut` (probably extracted from `CTransaction`) into (new) `witness_utxo` field. The extraction routine will check that `prevout.hash` of the input in unsigned_tx and `prev_tx.GetTxId()` match.

@AdamISZ you might look into this re https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/536, in case you need to include protections from this attack into your code

**Comment by dgpv** [comment]
Note that explicit witness UTXO is potentially a breaking change, as before the checking for witness/non-witness UTXO was done with `isinstance(input.utxo, CTxOut)`. Now `input.utxo` may still be an instance of `CTransaction`, and what should be checked instead is `input.witness_utxo` which will be `None` for non-segwit inputs or `CTxOut` for segwit inputs.

I am not sure if I should bump the library version to 1.1.0 or leave at 1.0.6 with this potentially breaking change.

**Comment by AdamISZ** [comment]
Because of the recent discussion I re-read Greg Sanders' email from 2017 (that you link) recently and indeed, I agree that your strategy to approach the issue is practical and probably the right one: give wallet devs the opportunity to insist on a full `CTransaction` field as `utxo` for an input, but still leave the witness option available. I assume this will require a change to BIP174 (I do rather wish people would stop describing it as a bug in BIP143 though - that's a bit of a stretch, considering BIP143 only adds information under the sighash, though not 100% wrong).

Practical considerations: I guess there will be some change to the text of BIP174 but perhaps not any serialization/specification change (ie keytype 0x00 may now be used with segwit, but optional). I see you already dropped some notes on https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/536 indicating this point: how a user of PSBTs makes a decision about input type can change, so I agree that's on me to fix that up for my use case.

About more general implications for Joinmarket: bear in mind that I deliberately did not include any proper general coinjoin PSBT support in that PR; the only thing it allows for any normal transaction (coinjoin or not) is, to optionally give a fully signed PSBT serialization instead of raw tx hex, in case that's useful in some rare case. I didn't yet want to think through possible implications if someone wanted to start using our wallet to sign partially and then co-sign with hardware wallets, as that'll need thinking through the *first* of the attacks Sanders mentioned.

For the SNICKER use case, there is a one way flow from a proposal to a half signed tx to being received by a JM user who then signs exactly one input (the specification requires it), locally, then broadcasts (or not as he chooses). There is no case where the JM user would be signing and creating a not-fully signed tx (if there was, then that could at least theoretically open up attacks of this type).

I may well have more comments when I address your review, and thanks for that.

**Comment by AdamISZ** [comment]
By the way I asked Andrew Chow and it sounds like there will be no meaningful change to the BIP174 specification (except in the Signer role).

**Comment by dgpv** [comment]
@AdamISZ Thank you for your comments! I've bumpet the version to v1.1.0.dev0, but will still wait to tag a release for a while.
